node( 'maven' ) {

    stage('Checkout'){
        checkout scm
    }

    stage('Build base image'){
        login()
        sh """
            oc start-build base-layer-java --from-dir=base-layer-java --follow=true
        """
    }

  
  stage('Promote') {
     input 'Make image available to all openshift users?'
     login()
     sh 'oc tag java:latest java:prod'
  }

}


def login() {
    sh """
       set +x
       oc login --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token) https://kubernetes.default.svc.cluster.local >/dev/null 2>&1 || echo 'OpenShift login failed'
       """
}






